### ISSUE TITLE
Consider enabling github pages

### ISSUE THREAD

**Issue by BlackCapCoder** [Sannadiana/FunProject#1]
Did you know you can host websites with Github?

It is a lot more convenient for people to try out your code if you do, because then they don't have to download your entire project.
You can enable Github pages from the settings menu, and if you do, the website should probably be available on [this link](http://sannadiana.github.io/FunProject/index.html).

Cheers!

**Comment by Sannadiana** [comment]
Nice, I did not know that, I will check that out, thanks ! 😄

**Comment by Sannadiana** [comment]
Now it's online and you do not have to download it. Thank you for a great feedback! @BlackCapCoder 👍

**Comment by BlackCapCoder** [comment]
Neato
